-- DMD007_Score.sql
-- 학생들의 과목 점수 더미 데이터
------------------------------------------------------------------------------------------------------------------------
-- 총 점수
------------------------------------------------------------------------------------------------------------------------
-- 1강의실
SELECT * FROM tblTotalScore;
DROP SEQUENCE totalscore_seq;
CREATE SEQUENCE totalscore_seq;

--1강의실 1번과목
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 26, 17, 1, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 39, 11, 2, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 38, 20, 3, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 33, 37, 20, 4, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 34, 36, 20, 5, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 35, 35, 17, 6, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 36, 34, 15, 7, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 37, 33, 20, 8, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 38, 32, 20, 9, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 39, 31, 20, 10, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 40, 30, 19, 11, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 20, 30, 17, 12, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 21, 30, 12, 13, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 22, 30, 20, 14, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 23, 30, 20, 15, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 24, 30, 16, 16, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 30, 10, 17, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 26, 30, 20, 18, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 27, 30, 20, 19, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 28, 30, 16, 20, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 29, 30, 17, 21, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 20, 20, 22, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 21, 20, 23, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 22, 18, 24, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 23, 14, 25, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 24, 20, 26, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 25, 18, 27, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 26, 19, 28, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 27, 12, 29, 1);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 25, 20, 30, 1);
  
--1강의실 2번과목
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 26, 20, 1, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 39, 20, 2, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 38, 12, 3, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 33, 37, 13, 4, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 34, 36, 20, 5, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 35, 35, 20, 6, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 36, 34, 16, 7, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 37, 33, 17, 8, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 38, 32, 20, 9, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 39, 31, 19, 10, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 40, 30, 20, 11, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 20, 30, 20, 12, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 21, 30, 10, 13, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 22, 30, 20, 14, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 23, 30, 20, 15, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 24, 30, 20, 16, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 30, 19, 17, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 26, 30, 18, 18, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 27, 30, 20, 19, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 28, 30, 20, 20, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 29, 30, 20, 21, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 20, 20, 22, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 21, 18, 23, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 22, 19, 24, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 23, 20, 25, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 24, 10, 26, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 25, 19, 27, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 26, 20, 28, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 27, 20, 29, 2);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 25, 14, 30, 2);

--1강의실 3번과목
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 26, 17, 1, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 39, 11, 2, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 38, 20, 3, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 33, 37, 20, 4, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 34, 36, 20, 5, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 35, 35, 17, 6, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 36, 34, 15, 7, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 37, 33, 20, 8, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 38, 32, 20, 9, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 39, 31, 20, 10, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 40, 30, 19, 11, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 20, 30, 17, 12, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 21, 30, 12, 13, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 22, 30, 20, 14, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 23, 30, 20, 15, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 24, 30, 16, 16, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 30, 10, 17, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 26, 30, 20, 18, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 27, 30, 20, 19, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 28, 30, 16, 20, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 29, 30, 17, 21, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 20, 20, 22, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 21, 20, 23, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 22, 18, 24, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 23, 14, 25, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 24, 20, 26, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 25, 18, 27, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 26, 19, 28, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 27, 12, 29, 3);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 25, 20, 30, 3);

-- 2강의실 4과목
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 40, 20, 31, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 39, 15, 32, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 38, 18, 33, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 33, 37, 2, 34, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 34, 36, 17, 35, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 35, 35, 13, 36, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 36, 34, 14, 37, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 37, 33, 1, 38, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 38, 32, 3, 39, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 39, 31, 19, 40, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 40, 30, 11, 41, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 20, 30, 17, 42, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 21, 30, 20, 43, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 22, 30, 4, 44, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 23, 30, 19, 45, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 24, 30, 11, 46, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 30, 18, 47, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 26, 30, 6, 48, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 27, 30, 17, 49, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 28, 30, 12, 50, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 29, 30, 14, 51, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 20, 16, 52, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 21, 10, 53, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 22, 7, 54, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 23, 3, 55, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 24, 12, 56, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 25, 15, 57, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 26, 18, 58, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 27, 16, 59, 4);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 28, 13, 60, 4);
   
-- 2강의실 5과목
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 40, 20, 31, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 39, 15, 32, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 38, 18, 33, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 33, 37, 2, 34, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 34, 36, 17, 35, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 35, 35, 13, 36, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 36, 34, 14, 37, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 37, 33, 1, 38, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 38, 32, 3, 39, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 39, 31, 19, 40, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 40, 30, 11, 41, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 20, 30, 17, 42, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 21, 30, 20, 43, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 22, 30, 4, 44, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 23, 30, 19, 45, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 24, 30, 11, 46, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 30, 18, 47, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 26, 30, 6, 48, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 27, 30, 17, 49, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 28, 30, 12, 50, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 29, 30, 14, 51, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 20, 16, 52, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 21, 10, 53, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 22, 7, 54, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 23, 3, 55, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 24, 12, 56, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 25, 15, 57, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 26, 18, 58, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 27, 16, 59, 5);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 28, 13, 60, 5);
   
-- 2강의실 6과목
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 40, 20, 31, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 39, 15, 32, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 38, 18, 33, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 33, 37, 2, 34, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 34, 36, 17, 35, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 35, 35, 13, 36, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 36, 34, 14, 37, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 37, 33, 1, 38, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 38, 32, 3, 39, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 39, 31, 19, 40, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 40, 30, 11, 41, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 20, 30, 17, 42, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 21, 30, 20, 43, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 22, 30, 4, 44, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 23, 30, 19, 45, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 24, 30, 11, 46, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 25, 30, 18, 47, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 26, 30, 6, 48, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 27, 30, 17, 49, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 28, 30, 12, 50, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 29, 30, 14, 51, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 30, 20, 16, 52, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 31, 21, 10, 53, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 22, 7, 54, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 23, 3, 55, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 24, 12, 56, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 25, 15, 57, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 26, 18, 58, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 27, 16, 59, 6);
INSERT INTO tblTotalScore(seq, PRACTICALSCORE, WRITINGSCORE, ATTENDANCESCORE, STUDENT_COURSESEQ, COURSE_SUBJECTSEQ) 
   VALUES (totalscore_seq.nextVal, 32, 28, 13, 60, 6);