-- DMD04_ConnectionInfo.sql
-- 각각의 정보를 연결하는 더미 데이터
---------------------------------------------------------------------------------------------------------------------
-- 교사 - 과목 데이터 더미(교사 : LoginSeq : 4 ~ 13)
---------------------------------------------------------------------------------------------------------------------
SELECT * FROM TBLTEACHER_SUBJECT;
CREATE SEQUENCE teacher_subject_seq;
DROP SEQUENCE teacher_subject_seq;
DELETE FROM TBLTEACHER_SUBJECT;

INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,4,1,1);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,4,2,2);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,4,3,3);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,5,4,4);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,5,5,5);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,5,6,6);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,6,7,7);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,6,8,8);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,6,9,9);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,7,10,10);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,7,11,11);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,7,12,12);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,8,13,13);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,8,14,14);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,8,15,15);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,9,16,16);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,9,17,17);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,9,18,18);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,10,19,19);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,10,20,20);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,10,21,21);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,11,22,22);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,11,23,23);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,11,24,24);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,12,25,25);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,12,26,26);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,12,27,27);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,13,28,28);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,13,29,29);
INSERT INTO TBLTEACHER_SUBJECT VALUES(teacher_subject_seq.nextVal,13,30,30);
---------------------------------------------------------------------------------------------------------------------
-- 과정 - 과목 데이터 더미
---------------------------------------------------------------------------------------------------------------------
SELECT * FROM TBLCOURSE_SUBJECT;
CREATE SEQUENCE course_subject_seq;
DROP SEQUENCE course_subject_seq;
DELETE FROM TBLCOURSE_SUBJECT;

INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 1, 1, 1, '2019-06-15', '2019-08-25');
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 2, 1, 2, '2019-08-26', '2019-10-25');
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 3, 1, 3, '2019-10-26', '2019-12-29');
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 4, 2, 4, '2019-05-26', '2019-07-26');
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 5, 2, 5, '2019-07-28', '2019-10-04');
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 6, 2, 6, '2019-10-05', '2019-12-26');
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 7, 3, 7, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 8, 3, 8, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 9, 3, 9, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 10, 4, 10, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 11, 4, 11, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 12, 4, 12, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 13, 5, 13,SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 14, 5, 14, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 15, 5, 15, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 16, 6, 16, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 17, 6, 17, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 18, 6, 18, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 19, 7, 19, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 20, 7, 20, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 21, 7, 21, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 22, 8, 22, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 23, 8, 23, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 24, 8, 24, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 25, 9, 25, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 26, 9, 26, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 27, 9, 27, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 28, 10, 28, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 29, 10, 29, SYSDATE, SYSDATE);
INSERT INTO TBLCOURSE_SUBJECT VALUES(course_subject_seq.nextVal, 30, 10, 30, SYSDATE, SYSDATE);
---------------------------------------------------------------------------------------------------------------------
-- 배점
---------------------------------------------------------------------------------------------------------------------
SELECT * FROM tblScorePoint;
CREATE SEQUENCE scorepoint_seq;
DROP SEQUENCE scorepoint_seq;
DELETE FROM tblScorePoint;

INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 20, sysdate, 40, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 20, sysdate, 40, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 20, sysdate, 40, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 20, sysdate, 40, sysdate, null);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 20, sysdate, null, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, null, sysdate, 40, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 50, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 30, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 40, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 50, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 30, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 50);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 30);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 50);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 30);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 20, sysdate, 0, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 30, sysdate, 0, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 40, sysdate, 0, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 20, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 30, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 40, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 20);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 30);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 40);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 20, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 30, sysdate, 0, sysdate, 0);
INSERT INTO tblScorePoint VALUES (scorepoint_seq.nextVal, 0, sysdate, 0, sysdate, 40);
---------------------------------------------------------------------------------------------------------------------
-- 교육생 - 과정 데이터 더미
---------------------------------------------------------------------------------------------------------------------
SELECT * FROM TBLSTUDENT_COURSE;
CREATE SEQUENCE student_course_seq;
DROP SEQUENCE student_course_seq;
DELETE FROM TBLSTUDENT_COURSE;

INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 14, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 15, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 16, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 17, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 18, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 19, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 2, '2019-09-26', 0, 1, 20, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 21, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 22, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 23, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 24, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 25, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 26, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 2, '2019-09-28', 0, 1, 27, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 28, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 29, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 30, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 31, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 32, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 33, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 34, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 35, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 36, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 37, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 38, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 39, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 40, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 41, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 42, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 1, 43, '2019-06-15');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 44, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 45, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 46, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 2, '2019-10-18', 0, 2, 47, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 48, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 49, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 50, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 51, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 52, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 53, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 54, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 55, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 56, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 2, '2019-10-15', 0, 2, 57, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 58, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 59, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 60, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 61, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 62, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 63, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 64, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 65, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 66, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 2, '2019-10-25', 0, 2, 67, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 68, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 69, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 70, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 71, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 72, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 73, '2019-05-05');
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 74, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 75, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 76, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 77, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 78, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 79, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 80, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 81, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 82, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 83, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 84, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 85, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 86, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 87, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 88, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 89, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 90, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 91, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 92, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 93, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 94, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 95, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 96, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 97, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 98, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 99, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 100, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 101, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 102, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 103, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 104, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 105, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 106, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 107, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 108, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 109, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 110, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 111, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 112, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 113, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 114, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 115, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 116, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 117, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 118, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 119, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 120, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 121, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 122, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 123, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 124, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 125, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 126, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 127, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 128, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 129, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 130, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 131, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 132, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 133, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 134, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 135, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 136, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 137, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 138, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 139, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 140, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 141, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 142, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 143, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 144, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 145, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 146, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 147, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 148, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 149, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 150, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 151, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 152, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 153, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 154, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 155, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 156, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 157, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 158, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 159, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 160, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 161, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 162, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 163, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 164, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 165, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 166, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 167, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 168, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 169, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 170, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 171, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 3, 172, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 3, 173, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 3, 174, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 3, 175, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 3, 176, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 177, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 178, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 179, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 180, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 181, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 182, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 183, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 184, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 185, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 186, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 187, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 188, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 189, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 190, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 191, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 192, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 193, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 194, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 195, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 196, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 197, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 198, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 199, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 200, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 201, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 202, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 203, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 204, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 205, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 206, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 207, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 208, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 209, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 210, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 211, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 212, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 213, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 214, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 215, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 216, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 217, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 218, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 219, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 220, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 221, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 222, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 223, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 224, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 225, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 226, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 227, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 228, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 229, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 230, DEFAULT);
INSERT INTO TBLSTUDENT_COURSE VALUES (student_course_seq.nextVal, 1, null, 0, 2, 231, DEFAULT);
---------------------------------------------------------------------------------------------------------------------